In [39]:
import pandas as pd

## Inspecting the scores a bit

In [57]:
dem_emotions_df = pd.read_csv('../data/emotion_scores/democrat_emails_emotions.csv')
df = pd.read_csv('../data/emotion_scores/emotion_scores_dcinbox_114.csv')
dem_emotions_df.head()
# spot checked these against emails in folder
"""
Date: 2016-06-17 - high sadness score - email is about her father's struggle with Alzheimer's
Date: 2016-02-19 - high sadness score - email is about National Cancer Prevention Month
Date: 2016-01-01 - high joy score - email is about her work in Congress
"""
sanchez_df = dem_emotions_df[dem_emotions_df['last_name'] == 'Sanchez'].copy()
sadness_df = sanchez_df[sanchez_df['sadness_score'] > 0.2].copy()
sadness_df.head()

,date,first_name,last_name,subject,joy_score,neutral_score,surprise_score,sadness_score,anger_score,fear_score,disgust_score
402,2016-02-19 16:40:00,Loretta,Sanchez,National Cancer Prevention Month 2016,0.026617,0.066021,0.016939,0.783021,NaN,0.102595,NaN
1412,2016-06-17 21:46:40,Loretta,Sanchez,Father's Day,NaN,0.030075,0.020062,0.897576,NaN,0.036228,0.009766
1470,2016-06-24 14:53:20,Loretta,Sanchez,Comprehensive Immigration Reform,NaN,0.080783,NaN,0.746760,0.043810,0.087639,0.026827
1545,2016-07-01 13:33:20,Loretta,Sanchez,Independence Day,0.091597,0.107438,NaN,0.526902,0.022728,0.235592,NaN
1984,2016-08-26 16:46:40,Loretta,Sanchez,Women's Equality Day,NaN,0.141578,NaN,0.514111,0.021294,0.252548,0.051690

In [59]:
all_emails_sanchez_sadness_df = df[df['last_name'] == 'Sanchez'].copy()
sadness_df = all_emails_sanchez_sadness_df[all_emails_sanchez_sadness_df['sadness_score'] > 0.5].copy()
sadness_df.head()

,date,first_name,last_name,subject,id,neutral_score,anger_score,joy_score,disgust_score,sadness_score,surprise_score,fear_score
11913,2016-02-19 16:40:00,Loretta,Sanchez,National Cancer Prevention Month 2016,109939.0,0.066021,NaN,0.026617,NaN,0.783021,0.016939,0.102595
15582,2016-06-17 21:46:40,Loretta,Sanchez,Father's Day,106544.0,0.030075,NaN,NaN,0.009766,0.897576,0.020062,0.036228
15753,2016-06-24 14:53:20,Loretta,Sanchez,Comprehensive Immigration Reform,106319.0,0.080783,0.043810,NaN,0.026827,0.746760,NaN,0.087639
15973,2016-07-01 13:33:20,Loretta,Sanchez,Independence Day,106057.0,0.107438,0.022728,0.091597,NaN,0.526902,NaN,0.235592
17458,2016-08-26 16:46:40,Loretta,Sanchez,Women's Equality Day,121835.0,0.141578,0.021294,NaN,0.051690,0.514111,NaN,0.252548

In [ ]:
# 19 sadness scores above 0.5
cooper = dem_emotions_df[dem_emotions_df['last_name'] == 'Cooper'].copy()
sadness_df = cooper[cooper['sadness_score'] > 0.5].copy()
# sadness_df.info()

# 26 fear scores above 0.5
fear_df = cooper[cooper['fear_score'] > 0.5].copy()
# 1 happy :)
joy_df = cooper[cooper['joy_score'] > 0.5].copy()
fear_df.head(10)
"""
Date: 2016-01-12 - high fear score - not convinced about this high score
Date 2016-02-10 - high fear score - drug overdoses
Date: 2016-03-17 - high fear score - Still, they fear risks from "global economic and financial developments." U.S. tightens sanctions on North Korea for weapons tests 
"""

,date,first_name,last_name,subject,joy_score,neutral_score,surprise_score,sadness_score,anger_score,fear_score,disgust_score
69,2016-01-12 12:00:00,Jim,Cooper,"Top 10 at 10: Tuesday, January 12",NaN,0.068878,0.008184,0.007179,0.006074,0.903298,NaN
208,2016-01-28 11:20:00,Jim,Cooper,"Top 10 at 10: Thursday, January 28",NaN,0.370528,0.039717,0.038985,0.020321,0.519363,NaN
322,2016-02-10 10:26:40,Jim,Cooper,"Top 10 at 10: Wednesday, February 10",NaN,0.196685,0.060978,0.011038,0.012293,0.707257,NaN
488,2016-02-29 12:46:40,Jim,Cooper,"Top 10 at 10: Monday, February 29",NaN,0.134767,0.025501,0.019080,0.015632,0.792268,NaN
552,2016-03-07 11:26:40,Jim,Cooper,"Top 10 at 10: Monday, March 7",NaN,0.062504,0.022528,0.032360,0.023764,0.851012,NaN
611,2016-03-14 10:06:40,Jim,Cooper,"Top 10 at 10: Monday, March 14",NaN,0.132165,0.021698,0.023914,0.030503,0.782024,NaN
634,2016-03-17 13:06:40,Jim,Cooper,"Top 10 at 10: Thurday, March 17",NaN,0.061327,0.005782,0.009231,0.015510,0.901975,NaN
981,2016-04-26 11:26:40,Jim,Cooper,"Top 10 at 10: Tuesday, April 26",NaN,0.284643,0.057304,0.101658,0.022756,0.516108,NaN
1374,2016-06-14 13:13:20,Jim,Cooper,"Top 10 at 10: Tuesday, June 14",0.017832,0.076641,0.018224,0.280519,NaN,0.596115,NaN
1396,2016-06-17 10:40:00,Jim,Cooper,"Top 10 at 10: Friday, June 17",0.008596,0.039070,0.011750,0.262732,NaN,0.669436,NaN

In [54]:
sample_data = dem_emotions_df.sample(50)
sample_data_df = pd.DataFrame(sample_data)
sample_data_df.to_csv('sample_data.csv', index=False)